project_id = "wtwruzxvkzlihisqvzlz"

[functions.send-otp-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.get-map-image]
verify_jwt = false

[functions.admin-hotels]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.track-affiliate-click]
verify_jwt = false

[functions.track-affiliate-conversion]
verify_jwt = false

[functions.generate-bulk-blog]
verify_jwt = true

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-password-reset-otp]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.sync-cannabis-laws]
verify_jwt = false
