project_id = "wtwruzxvkzlihisqvzlz"

[functions.send-otp-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.get-map-image]
verify_jwt = false

[functions.admin-hotels]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false